### ISSUE TITLE
Auth0 stored token refreshing

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/price-the-vintage#11]
The Auth0 token needs to be kept up to date on the client or the admin API will fail after the token times out.

**Comment by pablodefendini** [comment]
I'm seeing an Auth0-related failure when I try to log in, sign up, or any other authenticated action. Is that related to this issue, or. should I open a new one?

**Comment by jrmerz** [comment]
Probably due to related authentication work, are you accessing via HTTPS?

**Comment by pablodefendini** [comment]
ah, https works—thanks.

**Comment by jrmerz** [comment]
NP, and sorry we should have that as a redirect soon.

**Comment by jrmerz** [comment]
implementation of this issue will fix redirect issue: https://github.com/UCDavisLibrary/price-the-vintage/issues/8
