### ISSUE TITLE
Review the Info Page / Application Icon

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/price-the-vintage#14]
The Splash / Info page for the Price the Vintage application will have two prominent locations.  1) It will be the overall info page for the application itself.  2) It will basically be the card that is shown from the library site, that points to the applications.

The icon, ![The Icon](https://catalogs.wine-qa.library.ucdavis.edu/images/wine-icon-32.png),
 will also act as the phone icon button and the tab icon.  The icon currently is designed to be overlayed over a background color, as in: 
![image](https://cloud.githubusercontent.com/assets/344953/24921308/3ae72a94-1e9f-11e7-9eac-010b2a3a018f.png)

- [ ] Create a price-the-vintage-icon
- [ ] Review the description

## Description

Flipping through the pages of the Sherry-Lehmann catalog, produced by the famed New York City wine store, is like stepping back in time. From musings on wines by noted food and wine writer James Beard to charming descriptions of bottles stocked to captivating graphics, this is an immersive history at its finest.

As you flip through the catalogs, you might notice a lot of wine prices. We did too. Our goal is to take those dollar amounts and turn them into a searchable database to allow researchers and wine enthusiasts to chart changing prices and tastes. But to do that, we need your help in transcribing the prices that you see on the pages. So help us ‘Price the Vintage’

**Comment by pablodefendini** [comment]
Here's an icon to use:
![wine-app-icon](https://cloud.githubusercontent.com/assets/1683027/25132390/6bd3353a-2417-11e7-85b4-24f0411b926d.png)

**Comment by jrmerz** [comment]
Going to need in a couple different sizes, can I get as an SVG?

**Comment by pablodefendini** [comment]
Sent via slack, scene Github comments don't take SVG
