### ISSUE TITLE
Domain Names - How do we name applications.

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/price-the-vintage#15]
We need to decide on the best way to name our applications.  There are a number of possibilities.  For example, is the application is _price-the-vintage_ we could have (from shortest to longest)

-  _price-the-vintage_.org
-  _price-the-vintage_.ucdavis.edu
- [ x ]  **ptv.library.ucdavis.edu**  will be our default strategy.  We will include the library subdomain, but attempt to have just one name after that.  This will not be the case when we are collaborating with a multi-department team, in that case we'll move up to the ucdavis.edu domain.

## Addtional  Notes

The *.org* would require $13 year for subscription for each application, and namespace issues. The *.ucdavis.edu* would require us to work with UC directly for DNS, the *.lib* would require us to mint new ssl files for every application.  The *.wine.lib.ucdavis.edu* is easiest to update.  Also note, that for the library at least *.library.* is preferred from *.lib.*, so the above might also look like: _price-the-vintage_.library.ucdavis.edu

**Comment by qjhart** [comment]
@pbrantley , in our meeting @NeilWeingarten suggested that you have a strong, and complete decision on this.

**Comment by pbrantley** [comment]
My preferences are generally for short domain names; the use of "library."  whenever possible; avoiding domains like "specific.wine.library.." in favor of "specific.library..". the one exception would be for a product that might be vended, for example our future "Best of the Lot" PressForward application, which we would partner with V&E on development. 

I also personally dislike "-" in domain names. dislike progresses to detest when there are multiple hyphens. That's just me.
