### ISSUE TITLE
Marks x,y coordinates start from bottom, left corner

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/price-the-vintage#19]
@qjhart was this intended?

**Comment by qjhart** [comment]
Standard Image practice is to mark from the UL corner, w/ rows (y) being positive going down.  Standard Mapping posits y is positive going up, so when possible, I choose mapping coordinates.  That being said, I don't remember exactly what I did, but my recollection is that I put ORIGIN in LL corner, and specified mapping coordinates from there, as in:  http://leafletjs.com/examples/crs-simple/crs-simple.html

**Comment by jrmerz** [comment]
K, yes, currently we just pull the x,y value from leaflet and set it to the mark, which has origin LL.

Then only tricky bit is for things like the admin interface, when I want place a mark on a static image, I must first load the image to know height, then I can make the mark.  Not a big deal just more and FYI.

Mostly I just wanted to make sure this was intended.
