### ISSUE TITLE
Easy testing cleanup

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/price-the-vintage#20]
@qjhart this might already be implemented and I just need to not me lazy and look up the query....   can we write a admin query to delete all approved marks where the page section == 'test'?

**Comment by qjhart** [comment]
Get your token from your browser, and then:

```
url=http://api.catalogs.qjhart.org
token=[token]
http DELETE ${url}/marks Authorization:"Bearer ${token}" section==eq.test
```
