### ISSUE TITLE
View Mark (Disabled Input Form) UI

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/price-the-vintage#22]
When viewing marks, whether you are a user viewing a pending mark that you didn't create or anyone viewing a approved mark, the app now shows the input form with all inputs marked as disabled.  The current default styling for this is muted and a little disjoint between the drop downs and the input fields.

Example:
![screen shot 2017-04-13 at 9 51 03 am](https://cloud.githubusercontent.com/assets/1852393/25015090/2dae4c36-202f-11e7-922c-498dfcfc10d7.png)

@pablodefendini Can you take a crack at this?

**Comment by pablodefendini** [comment]
Yeah, the state you're looking for is 'idle and filled,' not 'disabled.' See the [material design spec](https://material.io/guidelines/components/text-fields.html#text-fields-states) for details. You'll want to make the color on the text be solid black, and the rules either solid and black as well, or remove them entirely (I would suggest removing them entirely).

**Comment by jrmerz** [comment]
@pablodefendini ok, so just clarify, no visual difference to show the field can no longer be edited?

**Comment by pablodefendini** [comment]
Yes, there should be visual differences: in the 'disabled' state, which is what's currently on the site (and showing in the screenshot above), the text is grey and the field has a grey, dotted bottom border. In the 'idle and filled' state, which is what I'm proposing you use for indicating that a field is not editable, the text is black and the field has a solid bottom border, or preferably no bottom border at all. 

Unrelated: I think I mentioned this before, but I also recommend removing the transparency from the form background entirely—it's unnecessarily confusing to have the text from the label image showing beneath the form field text.

**Comment by jrmerz** [comment]
Understood, but the 'idle and filled' state is also used when the form is editable and has a value, so the same state is being used for when a user: revisits their own pending mark (editing allowed), admin visits a pending mark (editing allowed), anyone visits an approved mark (and is therefore not allowed to edit).

**Comment by pablodefendini** [comment]
Yep.
