### ISSUE TITLE
Prepare the application for deployment

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/price-the-vintage#24]
We are soft rolling the price-the-vintage application, into the library setup,  For that we need the following administration.

- [x] Add UCD BIlling to the price-the-vintage google cloud project
I have added the user libgoogle@ucdavis.edu as an owner to the google cloud project.  libgoogle is the billing administrator for the UCD projects, and needs to update billing for this project to their billing information.  

- [x]  Domain access for ptv.library.ucdavis.edu.  
Since we are serving our client db from firebase, we can serve our static files there as well.  In order to do that, we need to use the firebase console, https://console.firebase.google.com/project/price-the-vintage/hosting/main/ and add a DNS TXT record to verify ownership of the dns location.  After that, need to add whatever is needed on our end to finalize that (CNAME / A) record. 

- [x]  Auth0 Authorization
Auth0 Authorization plugin is broken on our paid account.  Currently working with support to get this resolved.  This needs to be in place before the prototype can launch.

- [x] Certificate and DNS for wine-api.library.ucdavis.edu.  We need a DNS A record for wine-api.library.ucdavis.edu [169.237.102.155] and a certificate for that address as well.

**Comment by jniffenegger** [comment]
set the Library GCP billing to this project.

Can't do the domain add as it asks for the site verification using ucdavis.edu instead of library.ucdavis.edu. We do not have access to campus DNS.

**Comment by jniffenegger** [comment]
Found an alternate method to verify the domain name. It's added now.

**Comment by jrmerz** [comment]
@jniffenegger nice work!  I see the alternative described in docs, but not in the firebase console.  Where did you find it?

**Comment by jniffenegger** [comment]
@jrmerz in the GCP console under settings for the project, custom domains.

**Comment by jniffenegger** [comment]
though perhaps that only assigned i to the GCP project... I don't know how you then associate it to the firebase project...

**Comment by jrmerz** [comment]
Ya, that looks like it's wired up to the app engine settings.  I sent issue for the documentation to Firebase, see if we get a response.

Is it possible to setup a cname to price-the-vintage.firebaseapp.com?

**Comment by jniffenegger** [comment]
Yes, I set test.ptv.library.ucdavis.edu as cname to price-the-vintage.firebaseapp.com, however since the site doesn't know to recognize that domain, it loads using the SSL cert for price-the-vintage.firebaseapp.com which then makes your browser unhappy since the cert appears "invalid".

**Comment by jrmerz** [comment]
Right, SSL :/

**Comment by jrmerz** [comment]
All, FYI, I have opened a support ticket with firebase.  Will let you know when I hear back from them.

**Comment by jrmerz** [comment]
@jniffenegger Firebase support got back to me, said me the following: 

```
Hi there,
Thanks for reaching out! There actually a work around you can try to verify your subdomain.
Can you try visiting this site: https://www.google.com/webmasters/verification/verification?domain=your_subdomain_here?
If you can verify through there, the Firebase console should reflect the successful verification.

Let me know if you have any questions or if you run into any problems,
Wiley
```

Can you give this a go?

**Comment by jniffenegger** [comment]
That's the same method I already used to verify ptv.library.ucdavis.edu, but that applies it to our GCP account. I don't see any method to apply it to the firebase project. They need to give us more instructions on how that's done.

**Comment by jrmerz** [comment]
Ok, so just to verify, I'm going to reply that we did this method, it showed up under out GCP account (under app engine -> settings -> custom domains) but still does not show up in our domains list?

**Comment by jrmerz** [comment]
out of curiosity, what do you see here: https://www.google.com/webmasters/verification/home?hl=en

**Comment by jniffenegger** [comment]
It does show up under our domains list for google, via the link you just listed, but does not show up as a domain in the firebase console (I'm looking under the hosting section in firebase, if that's not the right place to look, let me know)

**Comment by jrmerz** [comment]
Humm, ya I think that's where it should show up.  I just let support know.

**Comment by jrmerz** [comment]
@jniffenegger 

Update from Firebase support:
```Thanks for the information. Can you try verifying again using library.ucdavis.edu instead and see if that works? (link https://www.google.com/webmasters/verification/verification?domain=library.ucdavis.edu)
If it doesn't, can you send a screenshot of the verification page from the webmaster verification tool to show the domain that has been verified and a screenshot of the Firebase console when you try to connect the domain again?```

**Comment by jniffenegger** [comment]
I've verified library.ucdavis.edu on the webmasters verification page using a CNAME just as I did with ptv.library.ucdavis.edu so they are both there now.

However, I still cannot add ptv.library.ucdavis.edu (or library.ucdavis.edu, even though we don't want to do that since that needs to point to our website) in the firebase console. It still wants to do a TXT verification against ucdavis.edu.

I've seen the screenshots to Justin.

**Comment by jrmerz** [comment]
Thanks, sent screenshots back to support.

**Comment by jrmerz** [comment]
k, next message...

```
Thanks for the information and sorry for the delay. Can you click into 
verification details and send a screenshot of what that returns?
Also did you verify library.ucdavis.edu using the TXT record or CNAME record?
```

**Comment by jniffenegger** [comment]
Sending the screens for the verification details of both library.ucdavis.edu and ptv.library.ucdavis.edu to Justin.

Are they just not plain getting it? Once again... We CAN NOT verify via TXT for ANYTHING under ucdavis.edu (since that's, technically, the parent domain) as we do not control it. Main campus does. We are not UC Davis, we are the UC Davis Library (library.ucdavis.edu). Thus, the only logical conclusion is that these were done via CNAME.

**Comment by jrmerz** [comment]
Support update:
```
Thanks for the screenshots. I've reached out to the backend engineers 
about this and it seems that there is a Firebase hosting UI bug that 
might be causing this issue. I'll let you know when I have more 
information about this.
```

**Comment by jrmerz** [comment]
Prototype Launched.  

Moved firebase hosting issue over to #29
