### ISSUE TITLE
Firebase Hosting - DNS Verification

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/price-the-vintage#29]
Moving part 2 of issue #24 over here so it can be tracked separate of the prototype rollout.

Currently waiting on Firebase engineers to look into hosting UI bug.

**Comment by jrmerz** [comment]
@jniffenegger it continues...

```
I've just heard back from the engineers that the bug should be fixed now.
Can you try adding ptv.library.ucdavis.edu in your Firebase hosting console 
and see if you can host the custom domain?
```

**Comment by jniffenegger** [comment]
It looks like it is going to work. Do you want me to go ahead? cuz it will require me to change the current DNS.

**Comment by jrmerz** [comment]
Let's plan on tomorrow AM?  Will give me tonight to verify the firebase hosted version is all set.

**Comment by jrmerz** [comment]
All set, switchover whenever.

**Comment by jniffenegger** [comment]
DNS changed. May take a while for google to see it. Still says "needs setup"  on the domain, though it is added now.

**Comment by jrmerz** [comment]
Ya, I'm getting to following from Firefox.  Looks like they didn't issue us a new cert:

![screen shot 2017-04-26 at 9 36 48 am](https://cloud.githubusercontent.com/assets/1852393/25445739/0996e30a-2a64-11e7-9eaf-cd564f002772.png)

**Comment by jniffenegger** [comment]
It has a note saying the cert can take an hour (I assume after it's happy w/ the DNS records).

**Comment by jrmerz** [comment]
Oooh.  Well I just sent an unhappy message to support....  Guess I'll give it an hour

**Comment by jniffenegger** [comment]
Might take more than an hour since the DNS has to update first. They likely have the old records cached.

**Comment by jrmerz** [comment]
DNS is updated on my end.

**Comment by jniffenegger** [comment]
If you're on our network, it would be as it's coming from our DNS. Everyone else, though, will depend on then their DNS last cached the record compared to the TTL we use, which is 1 day.

**Comment by jrmerz** [comment]
@jniffenegger Firebase still hasn't issued a SSL cert for the domain.  Can you please switch back the DNS (yet again) until we can verify the cert has been generated.  We need to have the site up since we have sent it out to people.

**Comment by jniffenegger** [comment]
I can change the DNS back, but can you confirm with them that the SSL cert is generated independent of the DNS being set? I have a feeling it's waiting to see the A records in place, which could take up to 24hrs from when I changed it depending when they cached the old records. So if we change the DNS back, it may never generate the SSL cert.

Let me know if you want me to go ahead with changing DNS back.

**Comment by jniffenegger** [comment]
Also, anyone that is now going to the new DNS could potentially take another 24hrs before they see it change back.

**Comment by jrmerz** [comment]
Yes, I am afraid of this as well, though since Firebase does not say this is the case, I was going to move forward under the assumption it is not.  Then raise more hell if it is.

Basically I'm a little stuck as this has been 'soft launched' and the site is now dead.  @qjhart please make the final call on how to proceed.

**Comment by jniffenegger** [comment]
FYI, firebase console now lists the custom domain as "pending" citing "this may take up to 2 hrs" .. not sure it would be good to stop now

**Comment by jrmerz** [comment]
Oooh, that is progress!

**Comment by jrmerz** [comment]
I have heard back from support.  So Firebase uses Let's Encrypt to issue certs.  Let's Encrypt has a limit on the number of certs it will issue in a given week (https://letsencrypt.org/docs/rate-limits/) which ucdavis.edu has hit.  Firebase is periodically attempting to issue a cert but failing.  So we are stuck until Firebase is able to get a cert from Let's Encrypt.

I have emailed back asking if we need our DNS pointed at the IP addresses provided by Firebase for the cert to be issued (I kinda guess this is the case, for verification purposes).  If so, we are really stuck.  If not, I would say we need to switch DNS back.

**Comment by jniffenegger** [comment]
Well in anticipation of something like this, yesterday I changed the TTL on the records to 5 minutes so if we need to switch back and forth, it should only take minutes, not a day, to propagate. Just let me know if/when you want the DNS changed.

**Comment by jrmerz** [comment]
According to firebase support:
```
Yes, you can move to another hosting provider while you wait for the certificate to get minted. 
You can try checking back on the 28th or the 2nd as based on the pattern that we are seeing 
in the certificate requests for UCD, it would be the most likely times that it would have gone 
through.
```

**Comment by jniffenegger** [comment]
DNS changed back to the wine-qa server.

**Comment by jrmerz** [comment]
Don't think this is happening.  Closing for now.
