### ISSUE TITLE
Dev domain

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/price-the-vintage#31]
Give a mouse a cookie...

@jniffenegger Can we get https://dev-pvt.library.ucdavis.edu as well?  Point at the same IP as pvt.library.ucdavis.edu.

@qjhart FYI.

**Comment by jniffenegger** [comment]
I assume you mean dev-ptv.

Done.

**Comment by jrmerz** [comment]
Ha, yes, thanks!
