### ISSUE TITLE
Milestone: New form input

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/price-the-vintage#35]
[Milestone]: https://github.com/UCDavisLibrary/price-the-vintage/milestone/5
[mockups]: https://drive.google.com/drive/u/0/folders/0B4y2_Xs4SL2-Wm5oQk1hcTZ5ZFk

This [Milestone] is mostly concerned with updating the PTV form input so that it more closely matches the input wine-search.  The most current [mockups] have most of the forms, but need some TLC on th

The current database schema needs to be adjusted; Remove media_id pointer in catalogs, and pages; remove production from marks; remove producer from prices;

There are many new cork-apps widgets need to be completed, and added to the system.

### Completion

This [Milestone] is considered complete when the production version of PTV has been updated with the new UI forms, as well as navigational parameters. 

If we decide on additional search components to support the menus, that's not in the scope of this milestone.

## Time Estimate

qjh: 24 hrs
jm: 60 hrs
kh: 24 hrs

**Comment by jrmerz** [comment]
@qjhart milestone is complete other than this issue, you want to be the one to close these out?
