### ISSUE TITLE
Milestone: PTV Update administration

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/price-the-vintage#36]
The current administration interface gives a good start to accepting pending marks. However, the actual way that the interface is used, doesn't match the intended workflow exactly. @qjhart and @wrenaria need to get together and go over the interface, to get a better idea of how the administrative interface might work.

Make sure to include:
- Where / How to land on a page mark 
 ( Quinn suggests the admin page shows just the pages with pending marks, and administrators are directed there.)
- Save vs. Accept
( If you edit and accept, it first saves)
- Updates to existing Marks
(Exisiting marks are editable, and just cause and update to wine-price-api)
- Display of current mark on page
(Make sure all marks can be seen at all times)

# Completion
This task is complete when we have a mockup that addresses the above issues, with any workflow included if it's not clear.

**Comment by qjhart** [comment]
@wrenaria, I'm assigning this task over to you, you should be able to access these pages on both [production] and [dev].

dev]:https://dev-ptv.library.ucdavis.edu
[production]:https://ptv.library.ucdavis.edu

**Comment by wrenaria** [comment]
Here's my initial thoughts on Admin interface update:

![ptvadmin-coreinterface](https://user-images.githubusercontent.com/17831969/28852107-9f49a0e0-76db-11e7-9d8e-1a0ce7821a41.jpg)

- Group marks by pages.

- Include image preview of page the marks are on and the title of the object.

- Last Updated can include most recent mark creation date lumped into it, unless there is a reason that creation date is important for sorting. Creation date of marks could vary when we are lumping pending marks together by page, so it seems like that's less important. 

Clicking on one of the cards will take you to the page with pending marks. Here's what the admin view of reviewing a pending mark looks like:

![ptvadmin-editmark](https://user-images.githubusercontent.com/17831969/28852187-2b07a29e-76dc-11e7-986e-b9dccf3f166c.jpg)

It's basically the same, but with Approve and Delete icons added.

In general, this is what I think is needed for mark icons sitewide:

![ptvadmin-markicons](https://user-images.githubusercontent.com/17831969/28852203-45098428-76dc-11e7-8d38-138abdfac34b.jpg)

If I'm missing any important admin features or if you have any other feedback, let me know.

My working file located at https://drive.google.com/open?id=0B4y2_Xs4SL2-ZWhmb1RnRWRNZ1k

**Comment by qjhart** [comment]
@wrenaria, this looks very nice, and closely matches my workflow.  With the marks associated by page, I can't really think if a `Sort by` constraint, and maybe we can remove that.

**Comment by wrenaria** [comment]
@qjhart All I could come up with for Sort was updated ascending, updated descending, and alphabetical. But if that's not helpful, then removing sort makes sense.

Looking to the future inclusion of labels and menus, do you want to be able to control what source you're reviewing? It might be helpful to toggle between viewing all sources, catalogs, labels, and menus.

**Comment by qjhart** [comment]
Hmm, that makes sense for menus (though we don't have a new 'thing' for menus, I was thinking they'd just be another catalog), but less for labels.  I wasn't thinking the label editing would be in this framework, but maybe we should think about that.  Off topic here though :)
