### ISSUE TITLE
UI development on PTV catalog and page display

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/price-the-vintage#38]
The forms are pretty well thought out, but the display of the catalogs and pages need to be finalized

**Comment by jrmerz** [comment]
Just started integrating our cork-elements into ptv, so could definitely use direction :)

**Comment by jrmerz** [comment]
@qjhart I made a board spectrum milestone about cork UI implementation (stuff not specific to the new form that is cropping up).  Did you want to move this card over there?

**Comment by qjhart** [comment]
[Mockups]:https://drive.google.com/open?id=0B4y2_Xs4SL2-Z3FKanJUYW1UcXM

I considered this to be complete with the [Mockups].
