### ISSUE TITLE
As an admin, I want to mark a page or catalogue as not-editable

### ISSUE THREAD

**Issue by pablodefendini** [UCDavisLibrary/price-the-vintage#4]

**Comment by pablodefendini** [comment]
maybe an icon on the side tools?

**Comment by jrmerz** [comment]
Note.  commit reference about was a typo.

**Comment by pablodefendini** [comment]
We can achieve that at the page level with a tool in the right hand toolbar (comp [here](https://invis.io/T89R5Y4CV#/228302295_Catalog_View_Admin_W_Tool_Tip)); for the whole catalogue, we can do it on the initial card view, as seen [here](https://invis.io/T89R5Y4CV#/228511305_Admin_Home).
