### ISSUE TITLE
Create new raster (png) icon for logo

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/price-the-vintage#44]
The logo must be generated with the proper background color (currently purple).  Also, I think this would be a decent time to discuss if @wrenaria had any tweaks she wanted done to the logo.

**Comment by jrmerz** [comment]
@wrenaria proposed the following [icons](https://drive.google.com/file/d/0B4y2_Xs4SL2-X2tnakp6RXFOeDQ/view). @wrenaria @qjhart was there a vote on these in this weeks meeting?

**Comment by qjhart** [comment]
Still reviewing, there is a 50-50 tie.

**Comment by jrmerz** [comment]
@wrenaria can I get the wine glass as a png icon w/ burgundy background (rounded corners if you want them) in the follow sizes?

- 16x16 (favicon)
- 32x23
- 48x48
- 64x64
- 96x96
- 128x128
- 192x192

**Comment by wrenaria** [comment]
I went totally round. I hope round is alright with you.

https://drive.google.com/drive/folders/0B4y2_Xs4SL2-TWh1aTUxY1I3MXM?usp=sharing 

Also I reversed the favicon colors because I think it reads a little better that way at that scale.

**Comment by jrmerz** [comment]
All look great to me! pushed to dev
