### ISSUE TITLE
Bottle type select list

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/price-the-vintage#50]
Using our custom cork-select element, the long select list creates a lot of extra space to scroll when open on the right hand panel.  See below.

![screen shot 2017-07-31 at 1 35 41 pm](https://user-images.githubusercontent.com/1852393/28797347-df3a7fb2-75f5-11e7-9bed-2730a996a83d.png)

@wrenaria how would you like to handle this?  You ok with it as is or change?

**Comment by wrenaria** [comment]
What about having scrolling within the dropdown list so the content box doesn't get unruly? Like we have in the Wine Search filters?

**Comment by jrmerz** [comment]
playing around with it, think that should work.  closing for now.  thanks!
