### ISSUE TITLE
Catalog and Page View Design Tweaks

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#52]
For the sake of better visual consistency across icons, I'd like the text and icons on the preview images to trade locations so that the right side sticky icons are always in the same spot whether or not the text next to them changes. Like so: 

![screen shot 2017-08-07 at 11 22 09 am](https://user-images.githubusercontent.com/17831969/29040392-b0bcb632-7b63-11e7-80c8-540e7c71112f.png)

![screen shot 2017-08-07 at 11 35 30 am](https://user-images.githubusercontent.com/17831969/29040620-8f34f74e-7b64-11e7-9944-ca502dfa64d1.png)

The page that the user is actually on should always be highlighted burgundy at the base so that they never lose where they are. Currently, the only indication is the active user icon, but if there are multiple active users in a catalog that won't be helpful. The outline can move with the click of the arrows to show that action. 

If there are no marks on a page, there should be no bottom color bar on the page preview image. 

The color bars on both the catalog and page previews should be slightly transparent - whatever it is on the current PTV site is probably a good amount. 

There is currently much too dark of a shadow behind the base for the page previews and no shadow behind the collapser tab (so it disappears when against white).

**Comment by jrmerz** [comment]
pushed to dev

**Comment by wrenaria** [comment]
Icon and highlight changes looks good, but missed some of my other notes. This screenshot with notes should help:

![icon-wine-artboard 1-100](https://user-images.githubusercontent.com/17831969/29049456-e22fe6d6-7b8a-11e7-93c5-eea2836b1264.jpg)

**Comment by jrmerz** [comment]
The above fixes to the carousel have been pushed.  

Note on the geometric shapes.  As with the triangle, creating custom shapes with drop shadow takes a lot of hacking around css.  Adding opacity to the mix made things even harder.  I have implemented a 'solution' but if you look very closely, you will see issues (And parts of the solution won't work in IE).  I am starting to think we should just make static raster assets (not SVG's but actual fix sized PNG's) for these UI elements when the crop up.

**Comment by jrmerz** [comment]
@wrenaria how are we looking on this ticket?

**Comment by wrenaria** [comment]
Uhhhh.... right. Well...

We can forgo transparency on this element if it causes problems. 

Both the code route and the raster route for shadows have issues. It's difficult to match the shadow style via raster. Like the triangle on the drop down boxes drives me crazy because of how unlike the box shadow it is (I've been thinking I will make a new one to try and get closer to the style). The code shadows are much closer, style-wise. But you're the code expert, so if you think raster is the way to go for a more consistent experience, I'll get those made today.

**Comment by jrmerz** [comment]
Well let's try a raster before we give up and remove opacity. The css box shadow I have been using is 10px spread with color rgba(0, 0, 0, .4).

**Comment by wrenaria** [comment]
Okay, let's give these a try...

Tab: https://drive.google.com/open?id=0B4y2_Xs4SL2-WU5RSjNIT0ZKTXM

New triangle: https://drive.google.com/open?id=0B4y2_Xs4SL2-Mm52Mjd4TnViazQ

**Comment by wrenaria** [comment]
As I sit here refreshing the page and pondering the animation effect, I just noticed the gray bars on the catalog images on the main page aren't transparent. they should be the same transparency as the gray bars on the page views.

**Comment by jrmerz** [comment]
pushed to dev

**Comment by wrenaria** [comment]
@jrmerz Where is this triangle issue at? Should the triangle be it's own issue to be dealt with at a later date?

**Comment by jrmerz** [comment]
Ya, let's actually move it over [here](https://github.com/cork-elements/cork-popup-button).
