### ISSUE TITLE
Margin below form (mobile)

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#54]
There's currently no space at the base of the form in mobile view. The button rests on the bottom of the browser

![screen shot 2017-08-07 at 12 23 38 pm](https://user-images.githubusercontent.com/17831969/29042344-6798902c-7b6b-11e7-91b1-9d06d88753ed.png)

There should be as much white space below the button as above it.

**Comment by jrmerz** [comment]
pushed to dev
