### ISSUE TITLE
Forms design tweak - dropdown icon and icon labels

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#57]
**Current site:**
![screen shot 2017-08-08 at 12 00 46 pm](https://user-images.githubusercontent.com/17831969/29089526-659f49f2-7c31-11e7-9081-3cf0c3434d67.png)

- The dropdown options boxes should be the same width as the dropdown base with the triangle part aligned to the mini burgundy triangle.

- Text underneath the wine/spirit icons should be the same size as text field font size and tiny bit lower down below the icon (it's a little cramped currently).

- The Fortified icon (only this one) turns purple when it's selected. This shouldn't happen. 

- Fortified is misspelled. 

- Since it's a long list, let's have the bottle sizes be listed alphabetically for easier scanning.

**With dropdown fixed:**
![better](https://user-images.githubusercontent.com/17831969/29093316-488ccf12-7c3e-11e7-8fac-878ec82d395e.jpg)

Also I noticed the checkmarks are not placed correctly on Firefox. Just fyi. (These are Chrome screenshots)

**Comment by jrmerz** [comment]
fixes pushed to dev
