### ISSUE TITLE
Thoughts on text size

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#58]
Right now there is slightly too much similarity between headers and input text.

My inclination is to drop the form headers from 14px to 12px and up their weight to 400px.

The input/body text can stay at 16px. In addition, the body copy on the front page catalog viewer/landing page should match this (the 14px currently being used feels a little small for reading whole paragraphs).

![screen shot 2017-08-08 at 2 43 44 pm](https://user-images.githubusercontent.com/17831969/29096407-ad1bbed8-7c49-11e7-85d9-d0d5885d51e7.png)
Headers: 12px - 400 weight
Content: 16px - 200 weight

---

I've been playing around with styles in-browser and I'm sort of pondering aloud here on a thing I keep going back and forth on... Do you like the all caps header text, or would title case text be easier to read? 

Example:
![lowercase](https://user-images.githubusercontent.com/17831969/29096337-4e474c88-7c49-11e7-9d19-354f5f4a1818.jpg)

**Comment by wrenaria** [comment]
For the sake of clarity, a size breakdown for all parts...
![icon-wine-logo1text1 100x-100](https://user-images.githubusercontent.com/17831969/29100859-44458dc0-7c63-11e7-8239-9f41b8e892c1.jpg)
![icon-wine-logo1text2 100x-100](https://user-images.githubusercontent.com/17831969/29100860-46fd5e58-7c63-11e7-8db8-dcac64200eb5.jpg)
![icon-wine-logo1text3 100x-100](https://user-images.githubusercontent.com/17831969/29100862-48af5c38-7c63-11e7-9786-e231c67b94e9.jpg)

**Comment by jrmerz** [comment]
My vote is for the CAPS labels on the inputs.  Like the difference.  Updates pushed to dev
