### ISSUE TITLE
Zoom/Marker/Search Button Treatment

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#59]
When viewing a catalog page...

1. The search, zoom, and marker placing icons should all be the same size. Right now search is much larger than the other two. (40 px vs 30) 

2. Also I'd like the marker icon to be the same shape as the actual marker that is placed for the sake of visual consistency. I've added an SVG for that here: https://drive.google.com/open?id=0B4y2_Xs4SL2-UUhwZU91dzdGUzA 

3. Search is currently the only element on the screen without shadow, so it should get similar shadow treatment as everything else. This will also help the white search box pop when it's open over a white background. 

4. I noticed shadows on these elements are reading more like outlines in Chrome, though they look fine in Firefox. Just fyi.

**Comment by jrmerz** [comment]
Sorry, I'm a little lost on some of these.

1) Do you want the other icons larger?  or the search icon smaller?  If the search icon smaller, then you want me to change the size of the search input box to a height of 30px as well?

2) So this is the replacing the current 'map pin' icon?

3) Can do

4) Do you prefer drop shadow or the 2px border.  Leaflet is applying a different set of styles in FF vs Chrome (not sure why)... but I can force whichever you prefer.

**Comment by wrenaria** [comment]
1. After closer evaluation, I'm gonna pull a Goldilocks here - let's go in between and make everything 35px high, the input box included. 
2. Yes. And the reason, if you're wondering, is that if there are existing pins on the page, it will be clearer to a user that this is what that button is for because it looks exactly the same shape as what's already there. I'm all for using as consistent visual language as possible. 
3. :)
4. Shadows

**Comment by jrmerz** [comment]
@wrenaria k, changes pushed to dev

**Comment by wrenaria** [comment]
The map pin marker icon image is too big. Should look more like this: 
![icon-sizing](https://user-images.githubusercontent.com/17831969/29228070-38fb7f3e-7e8d-11e7-8a38-2a13c77b9909.jpg)

Also I made an adjustment to the scale of the plus on the marker icon because the current one isn't working for me now that I see it in context. Here's the new version:  https://drive.google.com/open?id=0B4y2_Xs4SL2-UUhwZU91dzdGUzA

**Comment by jrmerz** [comment]
pushed to dev
