### ISSUE TITLE
Esc to close

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#62]
It's a common UX feature to have Esc close a thing. It'd be great if pressing Esc produced the same response as clicking the close or cancel buttons on the "Edit Mark," "View Mark," and Info pop up.

**Comment by jrmerz** [comment]
Pushed to dev

**Comment by wrenaria** [comment]
It's working on everything except the info pop up window. (Also clicking outside the box to close would be another common UX flow we could implement.)

**Comment by jrmerz** [comment]
pushed to dev
