### ISSUE TITLE
Moving a mark

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#63]
Right now you can only move a mark **after** you save it. There are two other instances it would be helpful to move a mark:

1. It would be helpful to be able to move a placed mark while in editing mode **before** you save it.

2. It would be helpful to be able move a pending mark as an admin. Right now, it is where it is and you can either accept or deny the mark. Tweaking placement might be helpful in some instances.

**Comment by jrmerz** [comment]
1) as we talked about, will be a bit of work as a plugin controls to the mark creation

2) pushed to dev

**Comment by wrenaria** [comment]
Great! Re: 1, Should we close this issue or leave it open for now?

**Comment by jrmerz** [comment]
Let's close for now, but open a new ticket for a later date feature enhancement.  Then we need to talk to @qjhart about how he wants to plan future development cycles.  My guess is we should be making a beta milestone and adding features to that.
