### ISSUE TITLE
Simplifying mark colors

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#64]
So I was looking at the info popup and playing with marks and noticed that only your own mark is brown, other people's marks are burgundy. 

Part of why I wanted pending marks to be brown to ease the adminning process - brown stands out enough from burgundy that it's easier to tell what needs to be approved. If only your own pending marks are brown that is less helpful.

I'm struggling to find a solution where you can both see your own marks and also ease the admin process, but at this point I am inclined to favor simplicity/admin process and move from this:

![markerlegend1](https://user-images.githubusercontent.com/17831969/29233036-b3a4f574-7ea3-11e7-8b45-d5ce5f452a13.jpg)

to this:

![markerlegend2](https://user-images.githubusercontent.com/17831969/29233039-b709d13a-7ea3-11e7-8418-313e30b930a1.jpg)

How important do you think it is it to differentiate your own marks at a glance? Is this something I need to think on more to find a solution? Maybe this is question for user testing question?

(@qjhart Feel free to weight in on this too.)

**Comment by wrenaria** [comment]
I'd also like to add that the info button in the header should probably be available on the front page as well since the icon legend on it also applies to that page. It currently is not.

**Comment by wrenaria** [comment]
What if we use another symbol instead? Like so:

![starartboard 6](https://user-images.githubusercontent.com/17831969/29236068-abcdeccc-7eba-11e7-91e5-927526ca71d9.jpg)

It might get lost on densely packed pages where things are stacked closely, but it would show for most of them without a problem.

**Comment by jrmerz** [comment]
pushed to dev

**Comment by wrenaria** [comment]
Nice! The pending marks are all showing as burgundy now. Make 'em brown and we can close this issue.

**Comment by jrmerz** [comment]
pushed to dev
