### ISSUE TITLE
Firefox Mark Creation bug

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#65]
When I try to create a mark in Firefox, this happens:

![screen shot 2017-08-11 at 2 59 08 pm](https://user-images.githubusercontent.com/17831969/29233511-04c2d596-7ea6-11e7-98f2-2964ae06ffed.png)

I get "View Mark" with no info instead of the form. 

Creating a mark seems to be working fine in Chrome and Safari.

**Comment by jrmerz** [comment]
@wrenaria Any further info you can provide?  I am unable to produce on Mac/Firefox v54.0.1

**Comment by wrenaria** [comment]
Huh. It seems to be working now. Odd. I guess let's close this issue?

**Comment by jrmerz** [comment]
Close it for now.  We can reopen later if we see it again.  This might have been related to a authentication issue that *I think* i fixed....
