### ISSUE TITLE
Info Pop-Up Window Images + Text

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#66]
Since we won't want the old images from old PTV in the info screen, I took new screenshots for the info pop up window. They are located here: https://drive.google.com/drive/folders/0B4y2_Xs4SL2-ZjlLR0JYcGJ4Q28?usp=sharing

Also this would be a nice time to clean up the type layout a little so that it matches the rest of the site and looks like this:
![infoscreen](https://user-images.githubusercontent.com/17831969/29236283-85630380-7ebd-11e7-9928-42c77b656708.jpg)

I included the star concept from issue #64, but we can leave that out if we don't go that route. The rest of alignment/layout concepts still apply. 

Here's a version with some mark up to help make things clearer:
![infoscreen-markup](https://user-images.githubusercontent.com/17831969/29236284-8c2d0bac-7ebd-11e7-9eaf-09bcb92f0301.jpg)

**Comment by wrenaria** [comment]
Also I altered the magnification tool text a bit, so here is the new copy for that:

**The magnification tools in the upper left allow you to zoom in and out of the catalog page you're on. Use the page browser at the bottom of the screen to go to the other pages in this catalog.**

**Comment by jrmerz** [comment]
This is mostly pushed to dev.  The left and right icon tables are tough to align because they are separate tables.  This allows them to drop from horizontal to vertical alignment on mobile.  I can go an make two separate table sets, one for mobile and one for desktop if you want.

**Comment by wrenaria** [comment]
No problem. It looks good as is, except the "Your marks" text is floating too high and in mobile there needs to be more space between the sections, since "Page Legend" is bumping up right against the icon from the previous section:

![screen shot 2017-08-14 at 10 16 16 am](https://user-images.githubusercontent.com/17831969/29283047-ebbb29d2-80d9-11e7-9e1b-c3ec8c378ad4.png)

I'd also prefer that the screenshot filled the width of the content area, like my mockup (https://drive.google.com/drive/u/1/folders/0B4y2_Xs4SL2-ZjlLR0JYcGJ4Q28)

**Comment by wrenaria** [comment]
Please capitalize the "how" in "Here's How" in the info screen title because everything else on that screen is in title caps and bothers me to no end every time I see it.

**Comment by jrmerz** [comment]
pushed to dev

**Comment by wrenaria** [comment]
![screen shot 2017-08-14 at 12 50 42 pm](https://user-images.githubusercontent.com/17831969/29288900-724b2fc8-80ef-11e7-8dad-b1b35b55d96e.jpg)
This one thing is not like the others...

**Comment by jrmerz** [comment]
pushed to dev
