### ISSUE TITLE
Admin Interface text adjustments

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#69]
Left is current style, right is updated style: 
![admininterface](https://user-images.githubusercontent.com/17831969/29285731-57467152-80e4-11e7-998f-5c781a60b388.png)

Single line catalog tiles are currently left aligned. They should always be centered.

**Comment by jrmerz** [comment]
@wrenaria Creating text that is:

- center aligned
- center justified
- creates ellipses on text overflow

It's really doable in CSS.   Please let me know how you would like to proceed.

**Comment by jrmerz** [comment]
pushed to dev

**Comment by wrenaria** [comment]
The weight on the catalog titles needs to upped to 400. It's currently 200.

**Comment by jrmerz** [comment]
pushed to dev
