### ISSUE TITLE
Price fields error in Firefox

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/price-the-vintage#70]
When using Firefox, when I put a price in, it throws an error if it's not a whole number.

![screen shot 2017-08-14 at 1 00 59 pm](https://user-images.githubusercontent.com/17831969/29289377-0ae38748-80f1-11e7-9811-7bc0c21078eb.png)

Seems to be fine in Chrome and Safari.

**Comment by jrmerz** [comment]
pushed to dev
